name: absensi_inkubis
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  dotted_border: ^2.0.0+3
  roundcheckbox: ^2.0.5
  intl: ^0.18.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.8.4
  dropdown_search: ^5.0.6
  image_picker: ^0.8.7
  firebase_storage: ^11.0.15
  cached_network_image: ^3.2.3
  geolocator: ^9.0.2
  location: ^4.4.0
  permission_handler: ^10.2.0
  numerus: ^2.0.0
  pdf: ^3.10.1
  open_filex: ^4.3.2
  printing: ^5.10.4
  blue_thermal_printer: ^1.2.3
  url_launcher: ^6.1.11
  hovering: ^1.0.4
  riverpod: ^2.3.6


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/


