// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3bJXPP_IPtbs0XJRFBDO717KMoEUXVhc',
    appId: '1:513743155198:web:77647e5dd28c5ef7e3daaf',
    messagingSenderId: '513743155198',
    projectId: 'inkubis-fe474',
    authDomain: 'inkubis-fe474.firebaseapp.com',
    storageBucket: 'inkubis-fe474.appspot.com',
    measurementId: 'G-PQN43D3965',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfEnJ6fE7JGv789b7XmmPKeWBmFuByDs8',
    appId: '1:513743155198:android:533b06ff11584507e3daaf',
    messagingSenderId: '513743155198',
    projectId: 'inkubis-fe474',
    storageBucket: 'inkubis-fe474.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVTQPD1wxkk5LoplBejmRR0Lmb9wgghcM',
    appId: '1:513743155198:ios:fbfd28991f6b1371e3daaf',
    messagingSenderId: '513743155198',
    projectId: 'inkubis-fe474',
    storageBucket: 'inkubis-fe474.appspot.com',
    iosClientId: '513743155198-7pgjlc623ru4lcg68gmlp8d828sgo07t.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiInkubis',
  );
}
